### ISSUE TITLE
a default constructor for catmull_rom?

### ISSUE THREAD

**Issue by xarthurx** [boostorg/math#212]
When trying to use this `catmull_rom` as a private member of a class, no matter what type `Point` is (say `Eigen::Vector2d>` here), there're always an error said 
`no default constructor exists for class boost::math::catmull_rom<Eigen::Vector2d>"`.

This usually will not happen to other constructors.

Would it be possible to provide an empty constructor for the class?

**Comment by NAThompson** [comment]
No, there is no default constructor for the Catmull-Rom class.

This is because the constructor computes the parametrization from the point set geometry. The class is therefore always in a valid state. A default constructor leaves the class in an invalid state.

There's almost always a way around the problem you are encountering, though I do feel your pain!

**Comment by xarthurx** [comment]
A pointer works, for the constructor.

However, if the class is designed to be used this way, a method similar to `at()` that works the same as `operator()` should be provided, similar to what `std::vector` has.

Otherwise, sth like `(*ptrToCatMullCrv)(t)` to get the value at `t` is really wired.

**Comment by NAThompson** [comment]
`at()` doesn't work that way: It does bounds checking on an integer index. It would definitely be surprising and non-idiomatic to use it in the way you are suggesting.

Personally, I don't see any problem with `(*ptr)(t)`.

**Comment by xarthurx** [comment]
OK, I'll use the `(*ptr)(t)` for now.
But IMHO, I don't think this issue is solved yet...
