### ISSUE TITLE
float_distance with arg promotion has surprising behavior

### ISSUE THREAD

**Issue by NAThompson** [boostorg/math#332]
Allowing two different template arguments in float_distance gives very surprising behavior, since it's not clear which floating point type the user intends to calculate the distance between.

If one type is integral, then this is sensible: Promote it to the floating point type. But if both are floating what is the intended behavior? The actual behavior is that it computes the more precise floating point distance.

**Comment by jzmaddock** [comment]
I'm unsure about this one, BTW for integral arguments things are potentially even more confusing because integer types are treated as `double`, so that `float_distance(0, float_value)` actually computes at double precision.

I'm tempted to suggest that we convert the mixed-arg version to static_assert internally with a reasonable helpful message and then see what breaks.  However, it is a breaking change, which would be too late for the next release I think (I'm hoping we might have time for one more merge of develop->release to include the wavelet code).

**Comment by NAThompson** [comment]
I'm make a PR for the breaking change and we can merge it at our convenience.
