### ISSUE TITLE
Log pdf support?

### ISSUE THREAD

**Issue by Svalorzen** [boostorg/math#525]
I was wondering whether there is, or there are plans to add, an interface to compute the `logpdf`s to the random distributions.

This would allow to more accurately manipulate probabilities without the need to first apply a log function to the output of the `pdf` and `cdf` functions.

**Comment by HDembinski** [comment]
👍 On this. When using the log-likelihood method, you need the logpdf instead of the pdf. Many common distributions are of the exponential family, so the logpdf is calculated naturally internally, and code that computes the log-likelihood then effectively does the superfluous log(exp(logpdf)).

The logpdf is also needed when additive models are used in a log-likelihood method. There is a numerically stable way to compute log(sum(exp(x1) + exp(x2))) (see https://numpy.org/doc/stable/reference/generated/numpy.logaddexp.html#numpy.logaddexp) where x1 and x2 are logpdf values.

**Comment by NAThompson** [comment]
A fast, numerically stable log-sum-exp seems like the natural place to start with this. I don't have much context for this problem; are there enough terms that it should it be parallelized?

@mborland

**Comment by mborland** [comment]
Is the linked PR the first step of what you are looking for @HDembinski? Like you said it's not overly difficult to add logpdf support by distribution.

**Comment by NAThompson** [comment]
@mborland : I think the hard part is getting the ULPs plots for all of these correct . . .

**Comment by HDembinski** [comment]
> Is the linked PR the first step of what you are looking for @HDembinski? Like you said it's not overly difficult to add logpdf support by distribution.

Yes, although the arcsine distribution is not the first that comes to mind. Ideal targets are the normal, poisson, exponential, beta, gamma, ...
