### ISSUE TITLE
Guidance for GSOC 2021

### ISSUE THREAD

**Issue by ameyachawla99** [boostorg/math#591]
Respected sir/madam

Hi , I am Ameya Chawla currently pursuing my B.Tech in Computer Science and Engineering .
I read about your organization in GSOC 2021 and looking forward to work with your organization .
I want to work on project Implement a feasible realization of FFT .

Please Guide me how should i start working

Thank You

**Comment by ckormanyos** [comment]
> work on project Implement a feasible realization of FFT
 > Please Guide me how should i start working
Hello Ameya,
Thank you for your interest in our projectand for your query. Since you found theproject, please consult its description atthat place.
As for moving forward, you need to formallyapply for this project using the established GSoCapplication procedure.
As written in other posts, you have to familiarizeyourself with the official GSoC guides for students.
Google offers extensive documentation on that.
If you have even more detailed questions, pleasefeel free to contact us via this thread.
Kind regards, Christopher Kormanyos
 

    On Monday, March 29, 2021, 7:35:18 PM GMT+2, ameyachawla99 ***@***.***> wrote:  
 
 


Respected sir/madam

Hi , I am Ameya Chawla currently pursuing my B.Tech in Computer Science and Engineering .
I read about your organization in GSOC 2021 and looking forward to work with your organization .
I want to work on project Implement a feasible realization of FFT .

Please Guide me how should i start working

Thank You

**Comment by ameyachawla99** [comment]
In Competency Test do we have to implement FFT or we can implement any transformation like Laplace transformation ?

Do we have to submit competency results in proposal or on github?

Thank You

**Comment by ckormanyos** [comment]
> In Competency Test do we have to implement FFT or we can implement any transformation like Laplace transformation ?

Please feel free to implement anything in that general area. This is a chance for you to show that you can handle programming numerical transformations. The selection of the exact transformation you choose is not the essential part of this competency expression.

> Do we have to submit competency results in proposal or on github?

In the past, successful candidates have posted the results of the competency test as a small repo on GitHub, GitLab or similar. This repo can be readily linked to within the larger scope of the application.

**Comment by ameyachawla99** [comment]
I have implemented FFT . 
Please can you review my code and guide me for any changes to be made.

https://github.com/ameyachawla99/math/tree/develop/FFT

**Comment by ckormanyos** [comment]
> I have implemented FFT.
> Please can you review my code and guide me for any changes to be made.

You might consider the variable `y` [at this line](https://github.com/ameyachawla99/math/blob/fc335f60919fde7121a9bd5fb0260224faabfcca/FFT/FastFourierTransform.cpp#L35). I believe the memory pointed to by `y` is allocated with `operator new`. In a very quick glance, I was not able to find the deletion of this complex-valued array.

You might consider another form of handling the result within the context of the recursive call or the FFT.

**Comment by ameyachawla99** [comment]
> You might consider another form of handling the result within the context of the recursive call or the FFT.
Should i change the implementation and use  different method to store results other than dynamic arrays?

**Comment by ameyachawla99** [comment]
>>I was not able to find the deletion of this complex-valued array.

I tried freeing the space using free method but "double free error was raised"  , i think they were freed when they were out of scope .
